
/* ===== Update: Sep 15 – Sep 29, 2026 (asset sale, entities, WC structure, RD Schedule 1) ===== */
KB.asOf = "Sep 29, 2026";
KB.source = "Contract Facts Ledger v14 + verified mail/Drive reads through Sep 29, 2026";
(function(){const c=KB.entities.find(e=>e.id==="claros"); if(c) c.blurb="Glen Surnamer's firm; he signs as Founder from Glen.Surnamer@claros.financial and as Partner of Woodland S LLC from gsurnamer@woodlandsouthcapital.com. Carried in Max's budget at $12,500 in September and $5,000/month after. No engagement letter located.";})();
KB.entities.push(
 {id:"wsclogi",type:"org",bucket:"internal",name:"WSC Logi Inc.",aliases:["WSC Logi","WSC Logi Inc","Logi"],blurb:"The entity Glen Surnamer says purchased the assets of SupplyNow Inc at auction on Sep 16, 2026, and the one the Sep 18 Penske call described as 'the primary operating entity for acquired logistics assets.' Delaware-style corporation established Aug 2026, EIN 42-4886321, doing business as SupplyNow, 35 Village Road Suite 100, Middleton MA 01949. Eight vehicles, about $2.3M annual revenue on the WEX application."},
 {id:"wscfin",type:"org",bucket:"internal",name:"WSC Finance LLC",aliases:["WSC Finance","Finance LLC"],blurb:"The entity Alvin named to Penske on Sep 22 as the buyer of SupplyNow's assets 'per the attached Bill of Sale.' Holds the Fleet One paperwork and is the lessee side of the executed Vehicle Sublease with SupplyNow Inc. Same address as WSC Logi: 35 Village Road Suite 100, Middleton MA 01949."},
 {id:"woodlands",type:"org",bucket:"advisor",name:"Woodland S LLC",aliases:["Woodland S","Woodland South Capital","WSC HQ"],blurb:"The Woodland South Capital partnership entity Alvin signs from as Managing Partner and Glen as Partner. 35 Village Road, Suite 100, Middleton, MA 01949. Alvin (617) 854-0055; Glen (646) 236-4737."},
 {id:"rachael",type:"person",name:"Rachael Zanni",aliases:["Rachael"],role:"VP Client Success, Woodland South Capital",blurb:"Schedules and coordinates WSC meetings with counterparties, including the Fleet One sessions."},
 {id:"sarah",type:"person",name:"Sarah Kledzik",aliases:["Sarah"],role:"Penske Truck Leasing, Cleveland District",blurb:"Sent the Feb 2026 default and termination letter for account 696207, and on Sep 23, 2026 declined future rentals to WSC Finance over the company's connection to the defaulted SupplyNow account."},
 {id:"luke",type:"person",name:"Luke Tannenbaum",aliases:["Luke"],role:"Justworks",blurb:"Justworks contact for the PEO onboarding. Told Glen on Sep 17 that no loss run is needed from the prior carrier because WSC Logi is a brand new EIN, but that the questionnaire should be answered on the predecessor company's history."},
 {id:"steven",type:"person",name:"Steven Schwartz",aliases:["Steven"],role:"Howden (insurance broker)",blurb:"Howden contact added by Alvin on the Penske certificate request. Handling the endorsement to add WSC Finance LLC, and per Alvin also WSC Logi Inc., as additional insureds."},
 {id:"t-wscvan",type:"truck",name:"WSC cargo van (Middleton)",aliases:["WSC van","cargo van","Chevy Express"],blurb:"The van WSC offered to replace or supplement a dry van. Sits at 35 Village Road, Suite 100, Middleton MA 01949. About 650 miles to Cleveland, roughly ten hours of driving. Open-carrier haul priced at $735 to $1,030 including the oversize surcharge. VIN, plate, title holder and mileage still unconfirmed."},
 {id:"t-hino19",type:"truck",name:"2019 Hino (VIN JHHRDM2HQKK007252)",aliases:["2019 Hino","JHHRDM2HQKK007252"],blurb:"Purchase candidate. Asking $22,900 at 163,340 miles, accepted at $20,500. Service record reviewed Sep 23 and described as thorough. Approved by Alvin subject to rust not becoming a major issue and reasonable residual value."},
 {id:"bwc",type:"system",name:"Ohio BWC (workers' compensation)",aliases:["BWC","Ohio Bureau of Workers' Compensation","workers comp"],blurb:"Ohio is one of four monopolistic states, so workers' compensation can only be bought from the state fund. A PEO cannot absorb it the way it would elsewhere: the PEO covers only payroll under its own tax ID, the client keeps its own policy, and a lease can only be entered on January 1 or July 1."},
 {id:"c-billofsale",type:"contract",name:"Bill of Sale (SupplyNow assets)",aliases:["Bill of Sale","asset sale"],blurb:"Attached by Alvin to Penske on Sep 22 as evidence that WSC Finance LLC bought the assets of SupplyNow. Glen's Sep 16 note to Aaron instead names WSC Logi Inc. as the purchaser at auction. The buyer of record has not been reconciled between the two."},
 {id:"c-sublease",type:"contract",name:"Vehicle Sublease Agreement (WSC Finance ↔ SupplyNow)",aliases:["Vehicle Sublease","Annex A","sublease"],blurb:"Executed between WSC Finance LLC and SupplyNow Inc so WSC Finance can lease the vehicles needed to run the business and sublease them back. Annex A requires Type of Vehicle, Manufacturer, Year, VIN and Owner for each unit and is still incomplete."},
 {id:"c-tla",type:"contract",name:"Transitional License Agreement",aliases:["TLA","transitional license"],blurb:"Sent by Alvin on Sep 23 for execution by SupplyNow Inc, covering use of the name while the change of name is pending. Routed to Aaron for signature via Glen. Mike noted on Sep 24 that nothing he has signed states he is an officer."}
);
KB.facts.push(
 {id:"F160",kind:"moment",date:"2026-09-16",text:"Glen Surnamer to Aaron, Sep 16: 'The auction has concluded, and WSC Logi Inc. has purchased the assets of SupplyNow Inc.' The Sep 18 Penske call summary describes WSC Logi as the entity that will become the primary operating entity for the acquired logistics assets.",ents:["wsclogi","glen","aaron","supplynow","penske"],src:"Gmail 1a0aa9c2a426f117; Read AI summary Sep 18",tab:"Entity & asset sale"},
 {id:"F161",kind:"finding",date:"2026-09-22",text:"Two different entities are named as the buyer of the same assets. Glen wrote on Sep 16 that WSC Logi Inc. purchased them at auction; Alvin wrote to Sarah Kledzik at Penske on Sep 22 that 'WSC Finance LLC bought the assets of SupplyNow, per the attached Bill of Sale.' The Vehicle Sublease and the Fleet One arrangement both run through WSC Finance. The buyer of record has not been reconciled.",ents:["wsclogi","wscfin","c-billofsale","alvin","glen","penske","sarah"],src:"Gmail 1a0aa9c2a426f117 and 1a0c932ff2f9a6e7",tab:"Entity & asset sale"},
 {id:"F162",kind:"definition",date:"2026-09-19",text:"WSC Logi Inc. on the WEX Fleet Card application: doing business as SupplyNow, EIN 42-4886321, 35 Village Road Suite 100, Middleton MA 01949, corporation established Aug 2026, Transportation and Warehousing, eight vehicles, about $2.3M annual revenue, about $10K a month of expected card spend. As a brand-new entity with no credit history it will likely draw a personal guaranty request before terms.",ents:["wsclogi","mike","glen"],src:"Mike to Glen, Sep 19 (Gmail 1a0ba3da6adf00ba)",tab:"Entity & asset sale"},
 {id:"F163",kind:"definition",date:"",text:"Every WSC entity shares one office: 35 Village Road, Suite 100, Middleton, MA 01949. WSC Finance LLC uses it on the Fleet One paperwork, WSC Logi Inc. carries it as its business address, and Alvin signs from it as Managing Partner of Woodland S LLC.",ents:["wsclogi","wscfin","woodlands","wsc","alvin"],src:"Mike to Ryan Shepherd, Sep 22; WEX application Sep 19",tab:"Entity & asset sale"},
 {id:"F164",kind:"moment",date:"2026-09-23",text:"Penske declined further business. Sarah Kledzik, Sep 23: 'we will not be able to provide any future rentals to WSC Finance due to the company's connection to a recently' defaulted account. The current rental was returned Sep 22. This is successor exposure surfacing with a live counterparty rather than in theory.",ents:["penske","sarah","wscfin","alvin","mike"],src:"Gmail 1a0c932ff2f9a6e7",tab:"Entity & asset sale"},
 {id:"F165",kind:"open",date:"2026-09-23",text:"Alvin rejected the Fleet One transfer form on Sep 23: it 'does not have the provisions that we need. Notably, we need to be able to explicitly sublease the unit back to SupplyNow Inc.' The working structure is WSC Finance holding the asset and subleasing to SupplyNow.",ents:["fleetone","wscfin","supplynow","alvin","ryan","c-sublease"],src:"Gmail 1a0d0414961e1ddb",tab:"Entity & asset sale"},
 {id:"F166",kind:"open",date:"2026-09-21",text:"The executed Vehicle Sublease between WSC Finance LLC and SupplyNow Inc needs Annex A completed: Type of Vehicle, Manufacturer, Year, VIN and Owner for every unit. Alvin asked Mike and Camille to fill it in as the go-forward fleet settles.",ents:["c-sublease","wscfin","supplynow","alvin","mike","camille"],src:"Alvin to Mike, Sep 21 (Gmail 1a0c4c921e024141)",tab:"Entity & asset sale"},
 {id:"F167",kind:"decision",date:"2026-09-18",text:"Alvin, Sep 18: 'SupplyNow Inc. is still the employer of record until we stand up our payroll platform and get everyone signed up to new employment / consulting agreements.' So the employing entity and the asset-owning entity are different right now, which is the fork that decides the Ohio workers' compensation filing.",ents:["supplynow","wsclogi","alvin","mike","bwc","justworks"],src:"Gmail 1a08790a1d748cb1",tab:"Payroll / PEO"},
 {id:"F168",kind:"finding",date:"2026-09-29",text:"Ohio is a monopolistic workers' compensation state, so coverage can only come from the Ohio BWC and a PEO cannot carry it as it would elsewhere. The PEO covers only payroll under its own tax ID, the client keeps its own BWC policy, and a PEO reporting lease can be entered only on January 1 or July 1. Justworks' November onboarding window therefore cannot carry the Ohio comp piece; the earliest is January 1.",ents:["bwc","justworks","supplynow","wsclogi","glen","mike"],src:"Ohio BWC PEO guidance and OAC 4123-17-02, reviewed Sep 29",tab:"Payroll / PEO"},
 {id:"F169",kind:"definition",date:"2026-09-29",text:"Ohio BWC succession: a successor who takes over a business in whole or in part must notify BWC on form U-118. On a whole succession BWC transfers the predecessor's experience and 'any and all existing and future liabilities or credits,' and may process the transfer without either party's signature. On a partial succession only the experience attributable to the portion acquired transfers. The successor must keep the predecessor's payroll records for the five years before the succession.",ents:["bwc","supplynow","wsclogi","wscfin","c-billofsale"],src:"OAC 4123-17-02 and 4123-17-51; BWC form U-118",tab:"Payroll / PEO"},
 {id:"F170",kind:"open",date:"2026-09-29",text:"Open on the van move: VIN, plate and state, registered owner, mileage, keys, and whether it is a cash sale, a capital contribution, or simply another line on Annex A of the existing sublease. Without the owner the Annex A line cannot be completed, and the title, registration, Ohio tax treatment and the named insured all follow that answer.",ents:["t-wscvan","wscfin","wsclogi","c-sublease","alvin","mike"],src:"Draft to Alvin, Sep 24",tab:"Trucks & disposition"},
 {id:"F171",kind:"number",date:"2026-09-24",text:"Moving the WSC cargo van from Middleton MA to Cleveland is about 650 miles and roughly ten hours of driving, eleven to twelve realistically. Open carrier runs $735 to $1,030 including the oversize surcharge for a full-size van. Driving it costs $550 to $750 once fuel, tolls, driver hours and a one-way flight are counted, but ties up a driver and puts the miles and the risk on the van.",ents:["t-wscvan","mike","alvin"],src:"Carrier rate research and route check, Sep 24",tab:"Trucks & disposition"},
 {id:"F172",kind:"decision",date:"2026-09-21",text:"Vehicle relocation request: unit 1003 back to Jeff in Elyria, estimated tow $600, drivable in limp mode at about 35 mph; unit 1007 to MH Leasing from Medina to Macedonia, estimated tow $350, must be towed; unit 1006 from Valley Freightliner to W.W. Williams for Mercedes-Benz engine service. Alvin held approval pending terms with Jeff.",ents:["t1003","t1007","t1006","hopkins","mh","mike","alvin","aaron"],src:"Gmail 1a0c5371d7a02c4a",tab:"Trucks & disposition"},
 {id:"F173",kind:"open",date:"2026-09-21",text:"Alvin, Sep 21, on the 1003 and 1007 tow fees: 'The two fees for those should not be an issue, especially as we can transfer the risk of loss in transit and driver's cost to a more suitable party.' In context the more suitable party reads as the lessor receiving the unit back. It has not been confirmed in writing who that is, and the same question is open for the van in transit.",ents:["t1003","t1007","alvin","mike","hopkins","mh"],src:"Gmail 1a0c5371d7a02c4a",tab:"Trucks & disposition"},
 {id:"F174",kind:"decision",date:"2026-09-15",text:"Alvin, Sep 15: proceed with notice on the MH Leasing contract, and keep working a plan to wind down the Quality Supply Limited and Kirill relationships. Separately, unless SupplyNow produces the AIT Software contract with concrete examples of what AIT does, WSC will reject that contract.",ents:["mh","qs","kirill","ait","alvin","mike","camille"],src:"Gmail 1a0a520aedf8477f",tab:"Order of operations"},
 {id:"F175",kind:"number",date:"2026-09-23",text:"2019 Hino, VIN JHHRDM2HQKK007252, 163,340 miles: asking $22,900, accepted at $20,500. Service record reviewed Sep 23 and described as thorough. Alvin approved subject to rust not becoming a major issue and reasonable residual value.",ents:["t-hino19","mike","alvin","ed"],src:"Gmail 1a0ca52394682c85",tab:"Trucks & disposition"},
 {id:"F176",kind:"definition",date:"2026-09-29",text:"The Restaurant Depot 2026 agreement has no numbered sections; it runs as unnumbered paragraphs. The only numbered list is the four immediate-termination triggers. Default markups are 13.5% delivery and 5% pickup, measured above the in-store shelf selling price and excluding taxes, bottle deposits and similar fees.",ents:["rd","c-rd-2026"],src:"Drive 1K_8KYY0h3VRxl1qjODmQ101NebxzniA8, read in full Sep 29",tab:"RD pricing tiers"},
 {id:"F177",kind:"finding",date:"2026-09-29",text:"Per-location margins live only in Schedule 1, not in the contract body. Its Base markups block is keyed by Store ID with four fields: requested pickup markup (current 5%), requested pickup fee (current $0), requested delivery markup (current 13.5%), and requested delivery fee, where the note reads 'Default delivery fee is $0 (you may already have a fee programmed into the website).' So the $50 delivery fee SupplyNow charges sits in JRD's system, not in the agreement, and moves on the same filing as the markups.",ents:["rd","c-rd-2026","pricing-dash","jaime"],src:"2026 Delivery Partner Agreement, Schedule 1",tab:"RD pricing tiers"},
 {id:"F178",kind:"definition",date:"2026-09-29",text:"Restaurant Depot customer discounts are keyed by member ID, separately from markups which are keyed by store ID. A discount record carries offer type (percent off, dollar off, or no delivery fee), offer amount, fulfillment type, a maximum reward per transaction, the applicable member IDs and the store IDs it applies to.",ents:["rd","c-rd-2026","pricing-dash"],src:"2026 Delivery Partner Agreement, Schedule 1",tab:"RD pricing tiers"},
 {id:"F179",kind:"open",date:"2026-09-23",text:"Transitional License Agreement sent by Alvin on Sep 23 for execution by SupplyNow Inc; the name change has not happened yet. Routed to Aaron for signature through Glen. Mike noted on Sep 24 that nothing he has signed states he is an officer of the company.",ents:["c-tla","alvin","aaron","glen","mike","supplynow"],src:"Gmail 1a0cf4b62393d10d",tab:"Entity & asset sale"}
);
KB.rels.push(
 ["wsclogi","supplynow","purchased the assets of (per Glen, Sep 16)","At auction; buyer of record not reconciled"],
 ["wscfin","supplynow","named as buyer of the assets of (per Alvin to Penske, Sep 22)","Per the attached Bill of Sale"],
 ["c-billofsale","supplynow","transfers the assets of",""],
 ["wsclogi","woodlands","under","Woodland South Capital"],["wscfin","woodlands","under","Woodland South Capital"],
 ["alvin","woodlands","Managing Partner of",""],["glen","woodlands","Partner of",""],["glen","claros","Founder of",""],
 ["rachael","woodlands","VP Client Success at",""],
 ["wscfin","fleetone","holds the lease paperwork with","Sublease back to SupplyNow required"],
 ["wscfin","supplynow","subleases vehicles to","Annex A incomplete"],
 ["c-sublease","wscfin","between",""],["c-sublease","supplynow","and",""],
 ["sarah","penske","at",""],["penske","wscfin","declined future rentals to","Sep 23, over the SupplyNow connection"],
 ["supplynow","bwc","files workers' compensation with","Monopolistic state fund"],
 ["wsclogi","bwc","must open its own policy with","New EIN; successor question open"],
 ["luke","justworks","at",""],["justworks","wsclogi","quoting the PEO for","Brand new EIN"],
 ["steven","nico","broker at Howden for",""],["steven","wscfin","adding as additional insured",""],
 ["t-wscvan","wsclogi","offered to",""],["t-wscvan","m-cleveland","to be moved to","About 650 miles from Middleton"],
 ["t-hino19","mike","sourced by","Approved subject to conditions"],
 ["c-tla","supplynow","for execution by","Name change pending"],
 ["mike","t-wscvan","arranging the haul for",""],
 ["alvin","c-billofsale","attached it to Penske",""]
);
